# mysql-external.yaml
# $ kubectl apply -f ./mysql-external.yaml
# $ kubectl run -it --rm --image=mysql:8.0.3 --restart=Never mysql-client --mysql -hmysqldb -rroot -ppassword
apiVersion: v1
kind: Service
metadata:
  name: mysqldb
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysqldb
subsets:
  - addresses:
    # FIXME: use the right IP
    - ip: 27.84.196.37
    ports:
      - protocol: TCP
        port: 3306
